
language: swift
osx_image: xcode11
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11
cache:
  - cocoapods
  - bundler
before_install:
    - gem install bundler
install:
    - bundle install
script:
    - fastlane build_and_test