
language: swift
osx_image: xcode12.2
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
cache:
  - cocoapods
  - bundler
befor_install:
    - gem install bundler
install:
    - bundle install
script:
    - fastlane build_and_test
env:
    - FB_REFERENCE_IMAGE_DIR = $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages
    - IMAGE_DIFF_DIR = $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/FailureDiffs