
language: swift
osx_image: xcode12.4
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
cache:
  - cocoapods
  - bundler
befor_install:
    - gem install bundler
install:
    - bundle install
script:
    - fastlane build_and_test